/* tslint:disable */
import './dashboard'
import './example'
import './eye-off'
import './eye-on'
import './form'
import './good-manager'
import './hamburger'
import './home'
import './icon_shouye '
import './icon-fahuoguanli'
import './icon-gerenzhongxin'
import './icon-yonghuguanli'
import './index'
import './link'
import './nested'
import './password'
import './personal-center'
import './platform-aliexpress'
import './table'
import './tree'
import './truck'
import './user-manager'
import './user'
import './wish'
